stages:
  - install
  - test
  - build

variables:
  NODE_ENV: development # Ensures devDependencies are installed during the pipeline

default:
  image: node:18
  cache:
    paths:
      - node_modules/

install_dependencies:
  stage: install
  script:
    - npm ci --legacy-peer-deps
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  tags:
    - shell 

run_tests:
  stage: test
  script:
    - npm test
  dependencies:
    - install_dependencies
  tags:
    - shell 

build_project:
  stage: build
  script:
    - npm run build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - shell   
