stages:
  - install
  - test
  - build

# Global Variables
variables:
  NODE_ENV: development  # Ensures devDependencies are installed during the pipeline
  GIT_DEPTH: 0 

# Default settings for all jobs
default:
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

# Install dependencies
install_dependencies:
  stage: install
  script:
    - npm ci --legacy-peer-deps || npm ci --legacy-peer-deps  # Retry if first fails
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  tags:
    - shell 

# Run Tests
run_tests:
  stage: test
  script:
    - npm test
  dependencies:
    - install_dependencies
  tags:
    - shell 

# Build Project
build_project:
  stage: build
  script:
    - npm run build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - shell    
