stages:
  - install
  - test
  - build

variables:
  NODE_ENV: development

default:
  image: node:18

install_dependencies:
  stage: install
  script:
    - npm ci --legacy-peer-deps
  cache:
    paths:
      - node_modules/

run_tests:
  stage: test
  script:
    - npm test
  dependencies:
    - install_dependencies

build_project:
  stage: build
  script:
    - npm ci --legacy-peer-deps
    - npm run build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
