stages:
  - install
  - test
  - build

variables:
  NODE_ENV: development # Ensures devDependencies are installed during the pipeline

default:
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

install_dependencies:
  stage: install
  script:
    - npm install --legacy-peer-deps

run_tests:
  stage: test
  script:
    - npm test
  dependencies:
    - install_dependencies

build_project:
  stage: build
  script:
    - npm install --legacy-peer-deps webpack webpack-cli # Ensure webpack is available
    - npm run build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
